#! python3

print("3.4")
names = ['Albert Einstein', 'Julius Cesar', 'Winston Churchill', 'Peter Parker', 'John Snow']
print("I want to invite you to dinner ", names[0])
print("I want to invite you to dinner ", names[1])
print("I want to invite you to dinner ", names[2])
print("I want to invite you to dinner ", names[3])
print("I want to invite you to dinner ", names[4], ".", "Please send me a reply if you come.")
msg = "I want to invite you to dinner "
print(msg, names[0])

print("3.5")
names = ['Albert Einstein', 'Julius Cesar', 'Winston Churchill', 'Peter Parker', 'John Snow']
print("I want to invite you to dinner ", names[0], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[1], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[2], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[3], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[4], ".", "Please send me a reply if you come.")

print("John Snow is unable to come to dinner.")
unable_come = 'John Snow'
names.remove(unable_come)
print(names)
names.append('Stephen Hawking')
print(names)
print("I want to invite you to dinner ", names[0], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[1], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[2], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[3], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[4], ".", "Please send me a reply if you come.")

print("3.6")
names = ['Albert Einstein', 'Julius Cesar', 'Winston Churchill', 'Peter Parker', 'John Snow']
print("I want to invite you to dinner ", names[0], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[1], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[2], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[3], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[4], ".", "Please send me a reply if you come.")

print("John Snow is unable to come to dinner.")
unable_come = 'John Snow'
names.remove(unable_come)
print(names)
names.append('Stephen Hawking')
print(names)
print("I want to invite you to dinner ", names[0], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[1], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[2], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[3], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[4], ".", "Please send me a reply if you come.")
print("\nI found a big table\t")
names.insert(0, 'Harry Potter')
names.insert(2, 'Elon Musk')
names.append('Platon')
print("\n")
print(names)
print("\n")
print("I want to invite you to dinner ", names[0], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[1], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[2], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[3], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[4], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[5], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[6], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[7], ".", "Please send me a reply if you come.")

print("3.7")
names = ['Albert Einstein', 'Julius Cesar', 'Winston Churchill', 'Peter Parker', 'John Snow']
print("I want to invite you to dinner ", names[0], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[1], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[2], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[3], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[4], ".", "Please send me a reply if you come.")

print("John Snow is unable to come to dinner.")
unable_come = 'John Snow'
names.remove(unable_come)
print(names)
names.append('Stephen Hawking')
print(names)
print("I want to invite you to dinner ", names[0], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[1], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[2], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[3], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[4], ".", "Please send me a reply if you come.")
print("\nI found a big table\t")
names.insert(0, 'Harry Potter')
names.insert(2, 'Elon Musk')
names.append('Platon')
print("\n")
print(names)
print("\n")
print("I want to invite you to dinner ", names[0], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[1], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[2], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[3], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[4], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[5], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[6], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[7], ".", "Please send me a reply if you come.")
print("\n")
remove_person = names.pop()
names.pop()
print("Sorry ", remove_person, ".", "I can't invite you because my table has only two seats.")
print(names)
print("\n")
remove_person = names.pop()
names.pop()
print("Sorry ", remove_person, ".", "I can't invite you because my table has only two seats.")
print(names)
print("\n")
remove_person = names.pop()
names.pop()
print("Sorry ", remove_person, ".", "I can't invite you because my table has only two seats.")
print(names)
print("\n")
print("I want to invite you to dinner ", names[0], ".", "Please send me a reply if you come.")
print("I want to invite you to dinner ", names[1], ".", "Please send me a reply if you come.")
del names[0]
del names[0]
print(names)